// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOKEN_ILLEGAL-0]
	_ = x[TOKEN_EOF-1]
	_ = x[TOKEN_IDENTIFIER-2]
	_ = x[TOKEN_CREATE-3]
	_ = x[TOKEN_INSERT-4]
	_ = x[TOKEN_INTO-5]
	_ = x[TOKEN_VALUES-6]
	_ = x[TOKEN_TABLE-7]
	_ = x[TOKEN_INDEX-8]
	_ = x[TOKEN_PRIMARY-9]
	_ = x[TOKEN_KEY-10]
	_ = x[TOKEN_LPAREN-11]
	_ = x[TOKEN_RPAREN-12]
	_ = x[TOKEN_COMMA-13]
	_ = x[TOKEN_SEMICOLON-14]
}

const _TokenType_name = "TOKEN_ILLEGALTOKEN_EOFTOKEN_IDENTIFIERTOKEN_CREATETOKEN_INSERTTOKEN_INTOTOKEN_VALUESTOKEN_TABLETOKEN_INDEXTOKEN_PRIMARYTOKEN_KEYTOKEN_LPARENTOKEN_RPARENTOKEN_COMMATOKEN_SEMICOLON"

var _TokenType_index = [...]uint8{0, 13, 22, 38, 50, 62, 72, 84, 95, 106, 119, 128, 140, 152, 163, 178}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
