// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOKEN_ILLEGAL-0]
	_ = x[TOKEN_EOF-1]
	_ = x[TOKEN_IDENTIFIER-2]
	_ = x[TOKEN_CREATE-3]
	_ = x[TOKEN_INSERT-4]
	_ = x[TOKEN_SELECT-5]
	_ = x[TOKEN_FROM-6]
	_ = x[TOKEN_INTO-7]
	_ = x[TOKEN_VALUES-8]
	_ = x[TOKEN_TABLE-9]
	_ = x[TOKEN_INDEX-10]
	_ = x[TOKEN_PRIMARY-11]
	_ = x[TOKEN_KEY-12]
	_ = x[TOKEN_LPAREN-13]
	_ = x[TOKEN_RPAREN-14]
	_ = x[TOKEN_COMMA-15]
	_ = x[TOKEN_SEMICOLON-16]
}

const _TokenType_name = "TOKEN_ILLEGALTOKEN_EOFTOKEN_IDENTIFIERTOKEN_CREATETOKEN_INSERTTOKEN_SELECTTOKEN_FROMTOKEN_INTOTOKEN_VALUESTOKEN_TABLETOKEN_INDEXTOKEN_PRIMARYTOKEN_KEYTOKEN_LPARENTOKEN_RPARENTOKEN_COMMATOKEN_SEMICOLON"

var _TokenType_index = [...]uint8{0, 13, 22, 38, 50, 62, 74, 84, 94, 106, 117, 128, 141, 150, 162, 174, 185, 200}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
